all: linux

linux:
	gcc -O2 -DPLATFORM_SDL -DVIEWPORT_WIDTH=176 -DVIEWPORT_HEIGHT=220 data.c draw.c main.c yeti.c -o Yeti3D.elf -lSDL

windows:
	gcc -O2 -DPLATFORM_SDL -DVIEWPORT_WIDTH=176 -DVIEWPORT_HEIGHT=220 data.c draw.c main.c yeti.c -o Yeti3D.exe \
		`sdl-config --cflags --libs`

clean:
	-rm -f *.o
	-rm -f *.elf
	-rm -f *.exe
