all: linux

linux:
	gcc -O2 -DPLATFORM_SDL data.c draw.c main.c yeti.c -o yeti3d.elf -lSDL

windows:
	gcc -O2 -DPLATFORM_SDL data.c draw.c main.c yeti.c -o yeti3d.exe `sdl-config --cflags --libs`

clean:
	-rm -f *.o
	-rm -f *.elf
	-rm -f *.exe
